sudo: required

services:
    - docker

before_install:
    - docker build -t sdraste07/visits .

script:
    - docker run sdraste07/visits npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push sdraste07/visits
